<?php

use Illuminate\Database\Seeder;

class CountryCodeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$currentTime = date("Y-m-d H:i:s");
		
        $countryCode = [
			['name' => 'AFGHANISTAN', 'iso3' => 'AFG', 'numcode'=> 4, 'phonecode'=> '+93'],
			['name' => 'ALBANIA', 'iso3'=> 'ALB', 'numcode' => '8', 'phonecode' => '+355'],
			['name' => 'ALGERIA','iso3' =>'DZA', 'numcode' => '12', 'phonecode' => '+213'],
			['name' => 'AMERICAN SAMOA', 'iso3' => 'ASM', 'numcode' => 16, 'phonecode' => '+1684'],
			['name' => 'ANDORRA', 'iso3' => 'AND', 'numcode' => 20, 'phonecode' => '+376'],
			['name' => 'ANGOLA', 'iso3' => 'AGO', 'numcode' => 24, 'phonecode' => '+244'],
			['name' => 'ANGUILLA', 'iso3' => 'AIA', 'numcode' => 660, 'phonecode' => '+1264'],
			['name' => 'ANTARCTICA', 'iso3' => NULL,'numcode' => NULL, 'phonecode' => '+0'],
			['name' => 'ANTIGUA AND BARBUDA', 'iso3' => 'ATG','numcode' => 28, 'phonecode' => '+1268'],
			['name' => 'ARGENTINA', 'iso3' => 'ARG', 'numcode' => 32, 'phonecode' => '+54'],
			['name' => 'ARMENIA', 'iso3' => 'ARM', 'numcode' => 51, 'phonecode' => '+374'],
			['name' => 'ARUBA', 'iso3' => 'ABW', 'numcode' => 533, 'phonecode' => '+297'],
			['name' => 'AUSTRALIA','iso3' => 'AUS', 'numcode' => 36,'phonecode' => '+61'],
			['name' => 'AUSTRIA', 'iso3' => 'AUT', 'numcode' => 40, 'phonecode' => '+43'],
			['name' => 'AZERBAIJAN','iso3' => 'AZE', 'numcode' => 31, 'phonecode' => '+994'],
			['name' => 'BAHAMAS','iso3' => 'BHS','numcode' => 44, 'phonecode' => '+1242'],
			['name' => 'BAHRAIN','iso3' => 'BHR', 'numcode' => 48, 'phonecode' => '+973'],
			['name' => 'BANGLADESH','iso3' => 'BGD', 'numcode' => 50, 'phonecode' => '+880'],
			['name' => 'BARBADOS','iso3' => 'BRB','numcode' => 52,'phonecode' => '+1246'],
			['name' => 'BELARUS','iso3' => 'BLR','numcode' => 112,'phonecode' => '+375'],
			['name' => 'BELGIUM','iso3' => 'BEL','numcode' => 56,'phonecode' => '+32'],
			['name' => 'BELIZE','iso3' => 'BLZ','numcode' => 84,'phonecode' => '+501'],
			['name' => 'BENIN','iso3' => 'BEN','numcode' => 204,'phonecode' => '+229'],
			['name' => 'BERMUDA', 'iso3' => 'BMU','numcode' => 60,'phonecode' => '+1441'],
			['name' => 'BHUTAN','iso3' => 'BTN','numcode' => 64,'phonecode' => '+975'],
			['name' => 'BOLIVIA','iso3' => 'BOL','numcode' => 68,'phonecode' => '+591'],
			['name' => 'BOSNIA AND HERZEGOVINA','iso3' => 'BIH', 'numcode' => 70,'phonecode' => '+387'],
			['name' => 'BOTSWANA','iso3' => 'BWA','numcode' => 72,'phonecode' => '+267'],
			['name' => 'BOUVET ISLAND','iso3' => NULL,'numcode' => NULL,'phonecode' => '+0'],
			['name' => 'BRAZIL', 'iso3' => 'BRA','numcode' => 76,'phonecode' => '+55'],
			['name' => 'BRITISH INDIAN OCEAN TERRITORY', 'iso3' => NULL,'numcode' => NULL, 'phonecode' => '+246'],
			['name' => 'BRUNEI DARUSSALAM','iso3' => 'BRN','numcode' => 96,'phonecode' => '+673'],
			['name' => 'BULGARIA','iso3' => 'BGR','numcode' => 100, 'phonecode' => '+359'],
			['name' => 'BURKINA FASO','iso3' => 'BFA','numcode' => 854, 'phonecode' => '+226'],
			['name' => 'BURUNDI','iso3' => 'BDI', 'numcode' => 108,'phonecode' => '+257'],
			['name' => 'CAMBODIA','iso3' => 'KHM','numcode' => 116,'phonecode' => '+855'],
			['name' => 'CAMEROON','iso3' => 'CMR','numcode' => 120,'phonecode' =>  '+237'],
			['name' => 'CANADA','iso3' => 'CAN','numcode' => 124,'phonecode' => '+1'],
			['name' => 'CAPE VERDE','iso3' => 'CPV','numcode' => 132,'phonecode' => '+238'],
			['name' => 'CAYMAN ISLANDS','iso3' => 'CYM','numcode' => 136,'phonecode' => '+1345'],
			['name' => 'CENTRAL AFRICAN REPUBLIC','iso3' => 'CAF','numcode' => 140,'phonecode' =>'+236'],
			['name' => 'CHAD','iso3' => 'TCD','numcode' => 148,'phonecode' => '+235'],
			['name' => 'CHILE','iso3' => 'CHL','numcode' => 152,'phonecode' => '+56'],
			['name' => 'CHINA','iso3' => 'CHN','numcode' => 156,'phonecode' => '+86'],
			['name' => 'CHRISTMAS ISLAND','iso3' => NULL,'numcode' =>  NULL,'phonecode' => '+61'],
			['name' => 'COCOS (KEELING) ISLANDS','iso3' => NULL,'numcode' => NULL,'phonecode' => '+672'],
			['name' => 'COLOMBIA','iso3' => 'COL','numcode' => 170,'phonecode' => '+57'],
			['name' => 'COMOROS','iso3' => 'COM','numcode' => 174,'phonecode' => '+269'],
			['name' => 'CONGO','iso3' => 'COG','numcode' => 178, 'phonecode' => '+242'],
			['name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','iso3' => 'COD','numcode' => 180,'phonecode' => '+242'],
			['name' => 'COOK ISLANDS','iso3' => 'COK','numcode' => 184,'phonecode' => '+682'],
			['name' => 'COSTA RICA','iso3' => 'CRI','numcode' => 188,'phonecode' => '+506'],
			['name' => "COTE D''IVOIRE",'iso3' => 'CIV','numcode' => 384,'phonecode' => '+225'],
			['name' => 'CROATIA','iso3' => 'HRV','numcode' => 191, 'phonecode' => '+385'],
			['name' => 'CUBA','iso3' => 'CUB','numcode' => 192,'phonecode' => '+53'],
			['name' => 'CYPRUS','iso3' => 'Cyprus','numcode' => 196,'phonecode' => '+357'],
			['name' => 'CZECH REPUBLIC','iso3' => 'CZE','numcode' => 203, 'phonecode' => '+420'],
			['name' => 'DENMARK','iso3' => 'DNK','numcode' => 208,'phonecode' => '+45'],
			['name' => 'DJIBOUTI','iso3' => 'DJI','numcode' => 262,'phonecode' => '+253'],
			['name' => 'DOMINICA','iso3' => 'DMA','numcode' => 212,'phonecode' => '+1767'],
			['name' => 'DOMINICAN REPUBLIC','iso3' => 'DOM','numcode' => 214,'phonecode' => '+1809'],
			['name' => 'ECUADOR','iso3' => 'ECU','numcode' => 218,'phonecode' => '+593'],
			['name' =>'EGYPT','iso3' => 'EGY','numcode' => 818,'phonecode' => '+20'],
			['name' => 'EL SALVADOR','iso3' => 'SLV','numcode' => 222,'phonecode' => '+503'],
			['name' => 'EQUATORIAL GUINEA','iso3' => 'GNQ','numcode' => 226,'phonecode' => '+240'],
			['name' => 'ERITREA','iso3' => 'ERI','numcode' => 232,'phonecode' => '+291'],
			['name' => 'ESTONIA','iso3' => 'EST','numcode' => 233,'phonecode' => '+372'],
			['name' => 'ETHIOPIA','iso3' => 'ETH','numcode' => 231,'phonecode' => '+251'],
			['name' => 'FALKLAND ISLANDS (MALVINAS)','iso3' => 'FLK','numcode' => 238,'phonecode' => '+500'],
			['name' => 'FAROE ISLANDS','iso3' => 'FRO','numcode' => 234,'phonecode' => '+298'],
			['name' => 'FIJI','iso3' => 'FJI','numcode' => 242,'phonecode' => '+679'],
			['name' => 'FINLAND','iso3' => 'FIN','numcode' => 246,'phonecode' => '+358'],
			['name' => 'FRANCE','iso3' => 'FRA','numcode' => 250, 'phonecode' => '+33'],
			['name' => 'FRENCH GUIANA','iso3' => 'GUF','numcode' => 254,'phonecode' => '+594'],
			['name' => 'FRENCH POLYNESIA','iso3' => 'PYF','numcode' => 258,'phonecode' => '+689'],
			['name' => 'FRENCH SOUTHERN TERRITORIES','iso3' => NULL,'numcode' => NULL,'phonecode' => '+0'],
			['name' => 'GABON','iso3' => 'GAB','numcode' => 266,'phonecode' => '+241'],
			['name' => 'GAMBIA','iso3' => 'GMB','numcode' => 270,'phonecode' => '+220'],
			['name' => 'GEORGIA','iso3' => 'GEO','numcode' => 268, 'phonecode' => '+995'],
			['name' => 'GERMANY','iso3' => 'DEU','numcode' => 276,'phonecode' => '+49'],
			['name' => 'GHANA','iso3' => 'GHA','numcode' => 288,'phonecode' => '+233'],
			['name' => 'GIBRALTAR','iso3' => 'GIB','numcode' => 292,'phonecode' => '+350'],
			['name' => 'GREECE','iso3' => 'GRC','numcode' => 300,'phonecode' => '+30'],
			['name' => 'GREENLAND','iso3' => 'GRL','numcode' => 304, 'phonecode' => '+299'],
			['name' => 'GRENADA','iso3' => 'GRD','numcode' => 308,'phonecode' => '+1473'],
			['name' => 'GUADELOUPE','iso3' => 'GLP','numcode' => 312,'phonecode' => '+590'],
			['name' => 'GUAM','iso3' => 'GUM','numcode' => 316, 'phonecode' => '+1671'],
			['name' => 'GUATEMALA','iso3' => 'GTM','numcode' => 320,'phonecode' => '+502'],
			['name' => 'GUINEA','iso3' => 'GIN','numcode' => 324,'phonecode' => '+224'],
			['name' => 'GUINEA-BISSAU','iso3' => 'GNB','numcode' => 624,'phonecode' => '+245'],
			['name' => 'GUYANA','iso3' => 'GUY','numcode' => 328,'phonecode' => '+592'],
			['name' => 'HAITI','iso3' => 'HTI','numcode' => 332,'phonecode' => '+509'],
			['name' => 'HEARD ISLAND AND MCDONALD ISLANDS','iso3' => NULL,'numcode' => NULL,'phonecode' => '+0'],
			['name' => 'HOLY SEE (VATICAN CITY STATE)','iso3' => 'VAT','numcode' => 336,'phonecode' => '+39'],
			['name' => 'HONDURAS','iso3' => 'HND','numcode' => 340,'phonecode' => '+504'],
			['name' => 'HONG KONG','iso3' => 'HKG','numcode' => 344,'phonecode' => '+852'],
			['name' => 'HUNGARY','iso3' => 'HUN','numcode' => 348,'phonecode' => '+36'],
			['name' => 'ICELAND','iso3' => 'ISL','numcode' => 352,'phonecode' => '+354'],
			['name' => 'INDIA','iso3' => 'IND','numcode' => 356,'phonecode' => '+91'],
			['name' => 'INDONESIA','iso3' => 'IDN','numcode' => 360,'phonecode'=> '+62'],
			['name' => 'IRAN, ISLAMIC REPUBLIC OF','iso3' => 'IRN','numcode' => 364,'phonecode' => '+98'],
			['name' => 'IRAQ','iso3' => 'IRQ','numcode' => 368,'phonecode'=> '+964'],
			['name' => 'IRELAND','iso3' => 'IRL','numcode' => 372,'phonecode' => '+353'],
			['name' => 'ISRAEL','iso3' => 'ISR','numcode' => 376,'phonecode' => '+972'],
			['name' => 'ITALY','iso3' => 'ITA','numcode' => 380,'phonecode' => '+39'],
			['name' => 'JAMAICA','iso3' => 'JAM','numcode' => 388,'phonecode' => '+1876'],
			['name' => 'JAPAN','iso3' => 'JPN','numcode' => 392,'phonecode' => '+81'],
			['name' => 'JORDAN','iso3' => 'JOR','numcode' => 400,'phonecode' => '+962'],
			['name' => 'KAZAKHSTAN','iso3' => 'KAZ','numcode' => 398,'phonecode' => '+7'],
			['name' => 'KENYA','iso3' => 'KEN','numcode' => 404,'phonecode' => '+254'],
			['name' => 'KIRIBATI','iso3' => 'KIR','numcode' => 296,'phonecode' => '+686'],
			['name' => "KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF", 'iso3' => 'PRK','numcode' => 408, 'phonecode' => '+850'],
			['name' => 'KOREA, REPUBLIC OF','iso3' => 'KOR','numcode' => 410,'phonecode' => '+82'],
			['name' => 'KUWAIT','iso3' => 'KWT','numcode' => 414, 'phonecode' => '+965'],
			['name' => 'KYRGYZSTAN','iso3' => 'KGZ','numcode' => 417,'phonecode' => '+996'],
			['name' => "LAO PEOPLE''S DEMOCRATIC REPUBLIC",'iso3' => 'LAO','numcode' => 418,'phonecode' => '+856'],
			['name' => 'LATVIA','iso3' => 'LVA','numcode' => 428,'phonecode' => '+371'],
			['name' => 'LEBANON','iso3' => 'LBN','numcode' => 422,'phonecode' => '+961'],
			['name' => 'LESOTHO','iso3' => 'LSO','numcode' => 426,'phonecode' => '+266'],
			['name' => 'LIBERIA','iso3' => 'LBR','numcode' => 430,'phonecode' => '+231'],
			['name' => 'LIBYAN ARAB JAMAHIRIYA', 'numcode' => 'LBY','numcode' => 434,'phonecode' => '+218'],
			['name' => 'LIECHTENSTEIN','iso3' => 'LIE','numcode' => 438,'phonecode' => '+423'],
			['name' => 'LITHUANIA','iso3' => 'LTU','numcode' => 440,'phonecode' => '+370'],
			['name' => 'LUXEMBOURG','iso3' => 'LUX','numcode' => 442,'phonecode' => '+352'],
			['name' => 'MACAO','iso3' => 'MAC','numcode' => 446,'phonecode' => '+853'],
			['name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','iso3' => 'MKD','numcode' => 807,'phonecode' => '+389'],
			['name' => 'MADAGASCAR','iso3' => 'MDG','numcode' => 450,'phonecode' => '+261'],
			['name' => 'MALAWI','iso3' => 'MWI','numcode' => 454,'phonecode' => '+265'],
			['name' => 'MALAYSIA','iso3' => 'MYS','numcode' => 458,'phonecode' => '+60'],
			['name' => 'MALDIVES', 'iso3' => 'MDV','numcode' => 462,'phonecode' => '+960'],
			['name' => 'MALI', 'iso3' => 'MLI','numcode' => 466,'phonecode' => '+223'],
			['name' => 'MALTA','iso3' => 'MLT','numcode' => 470,'phonecode' => '+356'],
			['name' => 'MARSHALL ISLANDS', 'iso3' => 'MHL','numcode' => 584,'phonecode' => '+692'],
			['name' => 'MARTINIQUE','iso3' => 'MTQ','numcode' => 474,'phonecode' => '+596'],
			['name' => 'MAURITANIA', 'iso3' => 'MRT','numcode' => 478,'phonecode' => '+222'],
			['name' => 'MAURITIUS', 'iso3' => 'MUS','numcode' => 480,'phonecode' => '+230'],
			['name' => 'MAYOTTE', 'iso3' => NULL,'numcode' => NULL,'phonecode' => '+269'],
			['name' => 'MEXICO', 'iso3' => 'MEX','numcode' => 484, 'phonecode' => '+52'],
			['name' => "MICRONESIA, FEDERATED STATES OF",'iso3' => 'FSM','numcode' => 583,'phonecode' => '+691'],
			['name' => 'MOLDOVA, REPUBLIC OF','iso3' => 'MDA','numcode' => 498,'phonecode' => '+373'],
			['name' => 'MONACO','iso3' => 'MCO','numcode' => 492,'phonecode' => '+377'],
			['name' => 'MONGOLIA', 'iso3' => 'MNG','numcode' => 496,'phonecode' => '+976'],
			['name' => 'MONTSERRAT', 'iso3' => 'MSR','numcode' => 500, 'phonecode' => '+1664'],
			['name' => 'MOROCCO','iso3' => 'MAR','numcode' => 504,'phonecode' => '+212'],
			['name' => 'MOZAMBIQUE','iso3' => 'MOZ','numcode' => 508,'phonecode' => '+258'],
			['name' => 'MYANMAR','iso3' => 'MMR','numcode' => 104,'phonecode' => '+95'],
			['name' => 'NAMIBIA', 'iso3' => 'NAM','numcode' => 516,'phonecode' => '+264'],
			['name' => 'NAURU','iso3' => 'NRU','numcode' => 520,'phonecode' => '+674'],
			['name' => 'NEPAL', 'iso3' => 'NPL','numcode' => 524,'phonecode' => '+977'],
			['name' => 'NETHERLANDS', 'iso3' => 'NLD','numcode' => 528,'phonecode' => '+31'],
			['name' => 'NETHERLANDS ANTILLES','iso3' => 'ANT','numcode' => 530,'phonecode' => '+599'],
			['name' => 'NEW CALEDONIA','iso3' => 'NCL','numcode' => 540,'phonecode' => '+687'],
			['name' => 'NEW ZEALAND', 'iso3' => 'NZL','numcode' => 554,'phonecode' => '+64'],
			['name' => 'NICARAGUA', 'iso3' => 'NIC','numcode' => 558,'phonecode' => '+505'],
			['name' => 'NIGER','iso3' => 'NER','numcode' => 562,'phonecode' => '+227'],
			['name' => 'NIGERIA', 'iso3' => 'NGA','numcode' => 566,'phonecode' => '+234'],
			['name' => 'NIUE','iso3' => 'NIU','numcode' => 570,'phonecode' => '+683'],
			['name' => 'NORFOLK ISLAND','iso3' => 'NFK','numcode' => 574,'phonecode' => '+672'],
			['name' => 'NORTHERN MARIANA ISLANDS','iso3' => 'MNP','numcode' => 580,'phonecode' => '+1670'],
			['name' => 'NORWAY','iso3' => 'NOR','numcode' => 578,'phonecode' => '+47'],
			['name' => 'OMAN', 'iso3' => 'OMN','numcode' => 512,'phonecode' => '+968'],
			['name' => 'PAKISTAN','iso3' =>'PAK','numcode' => 586, 'phonecode' => '+92'],
			['name' => 'PALAU', 'iso3' => 'PLW','numcode' => 585, 'phonecode' => '+680'],
			['name' => 'PALESTINIAN TERRITORY, OCCUPIED','iso3' => NULL,'numcode' => NULL,'phonecode' => '+970'],
			['name' => 'PANAMA','iso3' => 'PAN','numcode' => 591,'phonecode' => '+507'],
			['name' => 'PAPUA NEW GUINEA', 'iso3' => 'PNG','numcode' => 598,'phonecode' => '+675'],
			['name' => 'PARAGUAY', 'iso3' => 'PRY','numcode' =>  600,'phonecode' => '+595'],
			['name' => 'PERU', 'iso3' => 'PER','numcode' => 604,'phonecode' => '+51'],
			['name' => 'PHILIPPINES','iso3' => 'PHL','numcode' => 608,'phonecode' => '+63'],
			['name' => 'PITCAIRN', 'iso3' => 'PCN','numcode' => 612,'phonecode' => '+0'],
			['name' => 'POLAND','iso3' => 'POL','numcode' => 616,'phonecode' => '+48'],
			['name' => 'PORTUGAL','iso3' => 'PRT','numcode' => 620,'phonecode' => '+351'],
			['name' => 'PUERTO RICO', 'iso3' => 'PRI','numcode' => 630,'phonecode' => '+1787'],
			['name' => 'QATAR', 'iso3' => 'QAT','numcode' => 634,'phonecode' => '+974'],
			['name' => 'REUNION','iso3' => 'REU','numcode' => 638,'phonecode' => '+262'],
			['name' => 'ROMANIA','iso3' => 'ROM','numcode' => 642, 'phonecode' => '+40'],
			['name' => 'RUSSIAN FEDERATION','iso3' => 'RUS','numcode' => 643,'phonecode' => '+70'],
			['name' => 'RWANDA','iso3' => 'RWA','numcode' => 646,'phonecode' => '+250'],
			['name' => 'SAINT HELENA', 'iso3' => 'SHN','numcode' => 654,'phonecode' => '+290'],
			['name' => 'SAINT KITTS AND NEVIS', 'iso3' => 'KNA','numcode' => 659,'phonecode' => '+1869'],
			['name' => 'SAINT LUCIA','iso3' => 'LCA','numcode' => 662,'phonecode' => '+1758'],
			['name' => 'SAINT PIERRE AND MIQUELON', 'iso3' => 'SPM','numcode' => 666,'phonecode' => '+508'],
			['name' => 'SAINT VINCENT AND THE GRENADINES', 'iso3' => 'VCT','numcode' => 670, 'phonecode' => '+1784'],
			['name' => 'SAMOA','iso3' => 'WSM','numcode' => 882,'phonecode' => '+684'],
			['name' => 'SAN MARINO','iso3' => 'SMR','numcode' => 674,'phonecode' => '+378'],
			['name' => 'SAO TOME AND PRINCIPE', 'iso3' => 'STP','numcode' => 678,'phonecode' => '+239'],
			['name' => 'SAUDI ARABIA','iso3' => 'SAU','numcode' => 682,'phonecode' => '+966'],
			['name' => 'SENEGAL','iso3' => 'SEN','numcode' => 686,'phonecode' => '+221'],
			['name' => 'SERBIA AND MONTENEGRO','iso3' => NULL,'numcode' => NULL, 'phonecode' => '+381'],
			['name' => 'SEYCHELLES','iso3' => 'SYC','numcode' => 690,'phonecode' => '+248'],
			['name' => 'SIERRA LEONE', 'iso3' => 'SLE','numcode' => 694,'phonecode' => '+232'],
			['name' => 'SINGAPORE', 'iso3' => 'SGP','numcode' => 702,'phonecode' => '+65'],
			['name' => 'SLOVAKIA', 'iso3' => 'SVK','numcode' => 703,'phonecode' => '+421'],
			['name' => 'SLOVENIA','iso3' => 'SVN','numcode' => 705,'phonecode' => '+386'],
			['name' => 'SOLOMON ISLANDS','iso3' => 'SLB','numcode' => 90,'phonecode' => '+677'],
			['name' => 'SOMALIA', 'iso3' => 'SOM','numcode' => 706,'phonecode' => '+252'],
			['name' => 'SOUTH AFRICA', 'iso3' => 'ZAF','numcode' => 710,'phonecode' => '+27'],
			['name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','iso3' => NULL,'numcode' => NULL,'phonecode' => '+0'],
			['name' => 'SPAIN','iso3' => 'ESP','numcode' => 724, 'phonecode' => '+34'],
			['name' => 'SRI LANKA','iso3' => 'LKA','numcode' => 144,'phonecode' => '+94'],
			['name' => 'SUDAN','iso3' => 'SDN','numcode' => 736,'phonecode' => '+249'],
			['name' => 'SURINAME', 'iso3' => 'SUR','numcode' => 740,'phonecode' => '+597'],
			['name' => 'SVALBARD AND JAN MAYEN','iso3' => 'SJM','numcode' => 744,'phonecode' => '+47'],
			['name' => 'SWAZILAND','iso3' => 'SWZ','numcode' => 748,'phonecode' => '+268'],
			['name' => 'SWEDEN','iso3' => 'SWE','numcode' => 752, 'phonecode' => '+46'],
			['name' => 'SWITZERLAND','iso3' => 'CHE','numcode' => 756,'phonecode' => '+41'],
			['name' => 'SYRIAN ARAB REPUBLIC','iso3' => 'SYR','numcode' => 760,'phonecode' => '+963'],
			['name' => 'TAIWAN, PROVINCE OF CHINA','iso3' =>'TWN','numcode' => 158,'phonecode' => '+886'],
			['name' => 'TAJIKISTAN','iso3' => 'TJK','numcode' => 762,'phonecode' => '+992'],
			['name' => 'TANZANIA, UNITED REPUBLIC OF', 'iso3' => 'TZA','numcode' => 834,'phonecode' => '+255'],
			['name' => 'THAILAND', 'iso3' => 'THA','numcode' => 764,'phonecode' => '+66'],
			['name' => 'TIMOR-LESTE','iso3' => NULL,'numcode' => NULL,'phonecode' => '+670'],
			['name' => 'TOGO', 'iso3' => 'TGO','numcode' => 768,'phonecode' => '+228'],
			['name' => 'TOKELAU','iso3' => 'TKL','numcode' => 772,'phonecode' => 690],
			['name' => 'TONGA', 'iso3' => 'TON','numcode' => 776,'phonecode' => '+676'],
			['name' => 'TRINIDAD AND TOBAGO','iso3' => 'TTO','numcode' => 780,'phonecode' => '+1868'],
			['name' => 'TUNISIA','iso3' => 'TUN','numcode' => 788,'phonecode' => '+216'],
			['name' => 'TURKEY','iso3' => 'TUR','numcode' => 792,'phonecode' => '+90'],
			['name' => 'TURKMENISTAN','iso3' => 'TKM','numcode' => 795,'phonecode' => '+7370'],
			['name' => 'TURKS AND CAICOS ISLANDS','iso3' => 'TCA','numcode' => 796,'phonecode' => '+1649'],
			['name' => 'TUVALU','iso3' => 'TUV','numcode' => 798,'phonecode' => '+688'],
			['name' => 'UGANDA','iso3' => 'UGA','numcode' => 800,'phonecode' => '+256'],
			['name' => 'UKRAINE', 'iso3' => 'UKR','numcode' => 804, 'phonecode' => '+380'],
			['name' => 'UNITED ARAB EMIRATES', 'iso3' => 'ARE','numcode' => 784,'phonecode' => '+971'],
			['name' => 'UNITED KINGDOM','iso3' => 'GBR','numcode' => 826,'phonecode' => '+44'],
			['name' => 'UNITED STATES', 'iso3' => 'USA','numcode' => 840,'phonecode' => '+1'],
			['name' => 'UNITED STATES MINOR OUTLYING ISLANDS','iso3' => NULL,'numcode'=> NULL,'phonecode' => '+1'],
			['name' => 'URUGUAY','iso3' => 'URY','numcode' => 858,'phonecode' => '+598'],
			['name' => 'UZBEKISTAN', 'iso3' => 'UZB','numcode' => 860,'phonecode' => '+998'],
			['name' => 'VANUATU','iso3' => 'VUT','numcode' => 548,'phonecode' => '+678'],
			['name' => 'VENEZUELA','iso3' => 'VEN','numcode' => 862,'phonecode' => '+58'],
			['name' => 'VIET NAM','iso3' => 'VNM','numcode' => 704,'phonecode' => '+84'],
			['name' => 'VIRGIN ISLANDS, BRITISH','iso3' => 'VGB','numcode' => 92,'phonecode' => '+1284'],
			['name' => 'VIRGIN ISLANDS, U.S.','iso3' => 'VIR','numcode' => 850,'phonecode' => '+1340'],
			['name' => 'WALLIS AND FUTUNA','iso3' => 'WLF','numcode' => 876,'phonecode' => '+681'],
			['name' => 'WESTERN SAHARA','iso3' => 'ESH','numcode' => 732,'phonecode' => '+212'],
			['name' => 'YEMEN', 'iso3' => 'YEM','numcode' => 887,'phonecode' => '+967'],
			['name' => 'ZAMBIA','iso3' => 'ZMB','numcode' => 894,'phonecode' => '+260'],
			['name' => 'ZIMBABWE', 'iso3' => 'ZWE','numcode' => 716,'phonecode' => '+263']
		];
		DB::table('country_codes')->delete();
		foreach($countryCode as $code){
			DB::table('country_codes')->insert($code);
		}
    }
}
